using StrategyUnits;

Footman footman = new Footman();
Footman footman2 = new Footman();
Peasant peasant = new Peasant();
Cleric cleric = new Cleric();
footman2.ShowInfo();
footman.Attack(footman2);
footman2.ShowInfo();
footman.Attack(footman2);
footman2.ShowInfo();
cleric.HealSomebody(footman2);
footman2.ShowInfo();
footman.Attack(cleric);
cleric.ShowInfo();
cleric.RecoveryEnergy(cleric);
cleric.HealSelf(cleric);
cleric.ShowInfo();
peasant.PlowField();
peasant.PlowField();
peasant.FinishWork();
peasant.FinishWork();
footman.Attack(peasant);
peasant.ShowInfo();
