using StrategyUnits;

Footman footman = new Footman();
Footman footman2 = new Footman();
Peasant ps1 = new Peasant();
Cleric cleric = new Cleric();

ps1.ShowInfo();
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
ps1.ShowInfo();
cleric.CureSomebody(ps1);
ps1.ShowInfo();
cleric.ShowInfo();
cleric.RegenerationMana();
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
footman.InflictDamage(ps1);
cleric.CureSomebody(ps1);
cleric.ShowInfo();
footman.InflictDamage(cleric);
footman.InflictDamage(cleric);
footman.InflictDamage(cleric);
cleric.ShowInfo();
cleric.CureYourself(cleric);
cleric.ShowInfo();