using StrategyUnits;

Footman footman = new Footman();
Footman footman2 = new Footman();
Peasant peasant = new Peasant();
Cleric cleric = new Cleric();
footman2.ShowInfo();
footman.InflictDamage(footman2);
footman2.ShowInfo();
//footman.InflictDamage(footman2);
footman2.ShowInfo();
cleric.HealSomebody(footman2);
footman2.ShowInfo();
footman.InflictDamage(cleric);
cleric.ShowInfo();
cleric.RecoveryEnergy(cleric);
cleric.HealSelf(cleric);
cleric.ShowInfo();
peasant.PlowField();
peasant.PlowField();
peasant.FinishWork();
peasant.FinishWork();
footman.InflictDamage(peasant);
peasant.ShowInfo();
